name: Irene Y. Zhang
url: http://irenezhang.net
exclude: [bibble, README.md, Makefile]

# use this library to parse Markdown
markdown: redcarpet
redcarpet:
    extensions: [smart, tables]

# colorize code snippets with the pygment module
pygments: true

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Number of news stories on the front page.
front_page_news: 4

# Base pathname for links.
#base: 'http://irenezhang.net'
base: ''

# Navigation bar links.
navigation:
    - title: Home
      link: /
    - title: Research
      link: /research/
    - title: Publications
      link: /publications.html
    - title: Contact & c.
      link: /contact.html