name: Irene Y. Zhang
url: irenezhang.net
exclude: [bibble, README.md, Makefile]

# use this library to parse Markdown
markdown: redcarpet
redcarpet:
    extensions: [smart, tables]

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Number of news stories on the front page.
front_page_news: 4

# Base pathname for links.
base: '//irenezhang.net'

# Navigation bar links.
navigation:
    - title: Home
      link: /
    - title: Projects
      link: /research/
    - title: Publications
      link: /publications.html
    - title: Teaching
      link: /teaching.html
    - title: Code
      link: /code.html
    - title: CV
      link: /cv/cv.pdf